%==========================================================================
%Mechanical Verification
%David Tran
%{
Description: Simulates the axial displacement of a 1-dimensional fixed bar,
comparing them to results generated by Femap.
%}
%=============================Clear Cache==================================
clc; close all; clear all;


%=============================Constants====================================
E_mod = 4E11;                             %elastic modulus in [N/m^2]
A = 4E-4;                                 %cross-section area in [m^2]
L = 20E-2;                                %length of rod in [m]
P_0 = 444.8;                              %excitation force amplitude in [N]
omega = 2000 * pi;                        %frequency of excitation in [rad/s]
rho_L = 1.478;                            %mass per unit length in [kg/m]
N_pts = 100;                              %number of points


%==============================Arrays======================================
t = linspace(0, 2 * pi * 1.5 / omega, N_pts);    %time for 1.5 cycles
x = linspace(0, L, N_pts);                       %array to store x values
u = sym(zeros(N_pts, N_pts));


%============================Analytical Solution===========================
%nested for loop that iterates through all x for each t
syms j

h = waitbar(0,'Data loading...');
for i = 1:N_pts
    for k = 1:N_pts
        u(i, k) = (8 * P_0 * L)/(E_mod * A) * sin(omega * t(i)) * symsum((-1)^(j + 1)/(pi^2 * (2*j - 1)^2 - 4 * (omega * L * (sqrt(rho_L / (E_mod * A))))^2) * sin(((2*j - 1) * pi * x(k))/(2 * L)), j, [1 Inf]);
        waitbar(i/N_pts);
    end
end

%==============================Plot data===================================
set(gcf, 'Position',  [400, 100, 1000, 800]);
plot(t, double(u(:,N_pts)), 'LineWidth', 2);   %plot only the free end of the bar
xlabel('\textbf{Time (s)}', 'Interpreter', 'latex', 'FontSize', 20);
ylabel('\textbf{Displacement (m)}', 'Interpreter', 'latex', 'FontSize', 20);
title('\textbf{Displacement of Free End of Bar vs. Time}', 'Interpreter', 'latex', 'FontSize', 24);
grid on;